language: node_js
node_js:
  - "stable"

script:
  - npm install
  - npm test
  - npm run build

after_success:
  - npm install -g firebase-tools
  - firebase deploy --token "$FIREBASE_TOKEN"



on: 
  branch: master